---

- hosts: all
  become: true
  tasks:

  - name: update repo cache (Centos)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
       - apache2
       - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php packages for CentOS servers
    tags: httpd,php,centos
    apt:
      name:
       - httpd
       - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache, centos,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change e-mail address for admin
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "CentOS"
    register: httpd_email

  - name: restart httpd (CentOS)
    tags: apache,centos.httpd
    service:
      name: httpd
      state: restarted
    when: httpd_email.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_server
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: centos,mariadb,db
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: ubuntu,db,mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: add
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEIbyYWvc8hEDNDzq3RIGkwpq9kETNZ9gmlE5aGi0rOT ansible"

- hosts: workstation
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root


- hosts: file_server
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
